### ISSUE TITLE
A way to pass data to the renderer

### ISSUE THREAD

**Issue by nwazuo** [sibiraj-s/marked-react#2]
It would be nice if there was a way to pass data to the renderer via the `renderer` prop. 

Perhaps, instead of passing an object as a renderer, one could have the additional option of passing a function that returns the renderer object. This way I can pass in additional data from the component where I use `<Markdown>` component in, with maybe a `data` prop. This is just a suggestion of how it could work.

I find this useful if I want to style the output of a renderer token based on some data inside my component. 

E.g. 
If I had a `<Paragraph>` component that renders markdown text as a paragraph and I want to be able style that render output based on if the paragraph is supposed to be grayed out(this is passed as a prop to my component). 
```javascript
const Paragraph = (props) => {
 // suggested/proposed renderer function that returns renderer object
 let rendererFn = (data) => {
  let isGreyedOut = data.grey;

   return {
     paragraph(text) {
      React.createElement('p', {className: `${isGreyedOut && 'text-grey'}`}, text)
     }
   }
 }
 
  return (
    {/* data from my component is passed to the <Marked> 'renderer' prop(which now receives a function) via the proposed 'data' prop */}
    <Marked renderer={rendererFn} data={{isGreyedOut: props.isGreyedOut}} value={props.text}/>
    )
}
```

Don't know if this makes any sense...

**Comment by sibiraj-s** [comment]
Why not just directly invoke the function

```js
<Marked renderer={rendererFn({ grey: props.isGreyedOut })} value={props.text} />
```

or since the renderer is inside the component. why not just directly use the props?

**Comment by nwazuo** [comment]
Wow, brilliant! Never thought of that.  This has saved me from a great deal of over-engineering😅. This is why I love open source and collaboration. Thank you 👍
