### ISSUE TITLE
Property 'elementId' does not exist

### ISSUE THREAD

**Issue by bragovo** [sibiraj-s/marked-react#3]
When I create a custom renderer
```
const renderer = {
  paragraph(text: string) {
    return (
      <p key={this.elementId} className={s.paragraph}>
        {text}
      </p>
    )
  },
}
```
I've got an error `Property 'elementId' does not exist on type '{ paragraph(text: string): Element; }'.ts(2339)`. What I missed to use renderer with TS?

**Comment by sibiraj-s** [comment]
Appears be an issue with exported typings. Will check this out. Meanwhile PR's welcome.

**Comment by sibiraj-s** [comment]
Try v1.1.1. This should be fixed. Reopen if the problem still exists.

**Comment by Tobijudah** [comment]
hi @sibiraj-s this issue still exists in version 1.2.0
```
Property 'elementId' does not exist on type 'ReactRenderer | Partial<Omit<ReactRenderer, "elementId">>'.
  Property 'elementId' does not exist on type 'Partial<Omit<ReactRenderer, "elementId">>'.ts(2339)
```

**Comment by Tobijudah** [comment]
seems you're omitting the `elementId` here
```
type RendererObject = Partial<Omit<ReactRenderer, 'elementId'>>;
```
