### ISSUE TITLE
Highlighting text with <mark> is not working

### ISSUE THREAD

**Issue by lucarp** [sibiraj-s/marked-react#4]
The <mark> </mark> tags are being parsed as text instead of html tags to highlight the text.

**Comment by sibiraj-s** [comment]
can you provide a reproducible example?

**Comment by sibiraj-s** [comment]
Was able to reproduce this. `marked-react` only renders the valid markdown syntax as react components. <mark> is raw html and hence rendered as text.

The only way to render html is via using `dangerouslySetInnerHTML`, which is not supported.

**Comment by sibiraj-s** [comment]
May be can be allowed via an option `allowDangerousHTML` 🤔

**Comment by sibiraj-s** [comment]
Closing since parsing HTML is currently out of scope of this library.
