### ISSUE TITLE
Parse inline?

### ISSUE THREAD

**Issue by 4kimov** [sibiraj-s/marked-react#6]
Neat lib, thanks 👍

What's a good way to parse inline so that parent paragraph does not appear? (eg: `<p>stuff</p>` → `stuff`)

**Comment by sibiraj-s** [comment]
Are you try to parse HTML? HTML parsing ATM is not supported.

**Comment by 4kimov** [comment]
https://codesandbox.io/s/weathered-sky-bwlrq1?file=/src/App.js

Will produce:

```html
<div id="root">
  <p>stuff</p>
</div>
```

How can we make it produce:

```html
<div id="root">
  stuff
</div>
```

?

**Comment by sibiraj-s** [comment]
If You are targeting only inline content then you could do.

```js
const renderer = {
  paragraph(content) {
    return content;
  }
};

export default function App() {
  return <Markdown renderer={renderer}>stuff</Markdown>;
}
```

Othermeans to remove only the parent tag is currently not possible, I will look into this.

**Comment by sibiraj-s** [comment]
Try v1.2.0. Added support for inline markdown

Now you could do

```jsx
<Markdown isInline={true}>stuff</Markdown>
```

**Comment by 4kimov** [comment]
Nice, works as expected. Appreciate it 👍
